// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package apiV1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsUnknown(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UNKNOWN.String() && e.Code == 500
}

func ErrorUnknown(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UNKNOWN.String(), fmt.Sprintf(format, args...))
}

func ErrorMessageUnknown() *errors.Error {
	return errors.New(500, ErrorReason_UNKNOWN.String(), "未知错误")
}

func IsNotFount(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_NOT_FOUNT.String() && e.Code == 404
}

func ErrorNotFount(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_NOT_FOUNT.String(), fmt.Sprintf(format, args...))
}

func ErrorMessageNotFount() *errors.Error {
	return errors.New(404, ErrorReason_NOT_FOUNT.String(), "未知错误")
}
