// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	order2 "github.com/lyouthzzz/go-web-layout/internal/biz/order"
	"github.com/lyouthzzz/go-web-layout/internal/biz/user"
	"github.com/lyouthzzz/go-web-layout/internal/conf"
	"github.com/lyouthzzz/go-web-layout/internal/data"
	"github.com/lyouthzzz/go-web-layout/internal/facade/order"
	"github.com/lyouthzzz/go-web-layout/internal/server"
	"github.com/lyouthzzz/go-web-layout/internal/service"
)

// Injectors from wire.go:

func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData)
	usecase := user.NewUserUsecase(userRepo)
	userService := service.NewUserService(usecase)
	iOrderClient := order.NewClient()
	orderUsecase := order2.NewOrderUsecase(iOrderClient)
	orderService := service.NewOrderService(orderUsecase)
	grpcServer, err := server.NewGRPCServer(confServer, userService, orderService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	httpServer, err := server.NewHTTPServer(confServer, userService, orderService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
