server:
  http:
    network: tcp
    addr: :8080
    timeout: 10s
  grpc:
    network: tcp
    addr: :8081
    timeout: 10s
data:
  database:
    driver: mysql
    source: root:admin123@tcp(localhost:3306)/web_layout?charset=utf8mb4&parseTime=True&loc=Local